#!/bin/bash
cat /dev/null > ~/.ssh/config
echo "Host *" >> ~/.ssh/config 
echo "		ServerAliveInterval 99" >> ~/.ssh/config
echo "		ServerAliveCountMax 2" >> ~/.ssh/config
echo 'alias startvpn=\'~/vpnstart\'' >> ~/.bashrc
echo 'alias stopvpn=\'~/vpnstop\'' >> ~/.bashrc
