#!/bin/bash
iptables -F -t nat
iptables -t nat -A POSTROUTING -s 192.168.10.2 -j MASQUERADE
sysctl -w net.ipv4.ip_forward=1

#iptables -F INPUT
#iptables -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
#iptables -A INPUT -s 5.196.76.41/32 -p tcp --dport 2022 -j ACCEPT
#iptables -A INPUT -p tcp --dport 2022 -j DROP

sysctl --system #Reload settings from all system configuration files
sh -c "iptables-save > /etc/iptables.rules"
sh -c "exit"

