#!/bin/bash
#iptables -F -t nat
#iptables -t nat -A POSTROUTING -s 192.168.10.2 -j MASQUERADE
#sysctl -w net.ipv4.ip_forward=1

iptables -F INPUT
iptables -F FORWARD
iptables -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
iptables -A INPUT -s 213.135.240.0/24 -j ACCEPT
iptables -A INPUT -s 142.44.24.0/24 -j ACCEPT
iptables -A INPUT -s 212.83.176.0/24 -j ACCEPT
iptables -A INPUT -s 163.172.70.0/24 -j ACCEPT
iptables -A INPUT -s 213.124.160.0/24 -j ACCEPT
iptables -A INPUT -s 117.0.197.0/24 -j ACCEPT
iptables -A INPUT -s 107.170.213.0/24 -j ACCEPT
iptables -A INPUT -s 45.63.43.0/24 -j ACCEPT
iptables -A INPUT -s 184.154.72.0/24 -j ACCEPT
iptables -A INPUT -s 105.227.192.0/24 -j ACCEPT
iptables -A INPUT -s 213.135.240.0/24 -j ACCEPT
iptables -A INPUT -s 107.181.174.0/24 -j ACCEPT
iptables -A INPUT -s 163.172.112.0/24 -j ACCEPT
iptables -A INPUT -s 93.77.116.0/24 -j ACCEPT
iptables -A INPUT -s 42.112.84.0/24 -j ACCEPT
iptables -A INPUT -s 195.22.127.0/24 -j ACCEPT
iptables -A INPUT -s 193.9.28.0/24 -j ACCEPT
iptables -A INPUT -s 165.227.204.0/24 -j ACCEPT
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A FORWARD -j DROP
iptables -A INPUT -j DROP

sysctl --system #Reload settings from all system configuration files
sh -c "iptables-save > /etc/iptables.rules"
sh -c "exit"

